
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 30 00:31:38 CET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class DmSymbol {
  /* terminals */
  public static final int STRING_LITERAL = 56;
  public static final int FUNCTION = 48;
  public static final int LBRACKET = 27;
  public static final int MULT = 10;
  public static final int GE = 23;
  public static final int SEMIC = 6;
  public static final int INTEGER = 54;
  public static final int REPEAT = 53;
  public static final int MINUS = 8;
  public static final int CHARACTER = 60;
  public static final int NOT = 24;
  public static final int AND = 32;
  public static final int RCRO = 19;
  public static final int LT = 20;
  public static final int RPAR = 5;
  public static final int TYPE = 49;
  public static final int IN = 42;
  public static final int VIR = 36;
  public static final int OR = 33;
  public static final int COMMA = 16;
  public static final int CLASS = 50;
  public static final int DIV = 11;
  public static final int PLUS = 7;
  public static final int IF = 43;
  public static final int MAIN = 3;
  public static final int ID = 57;
  public static final int DOT = 30;
  public static final int LE = 22;
  public static final int OF = 14;
  public static final int BOOLEAN = 59;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int PLUSS = 37;
  public static final int LAND = 34;
  public static final int RBRACKET = 28;
  public static final int TRUE = 46;
  public static final int error = 1;
  public static final int LOR = 35;
  public static final int NULL = 51;
  public static final int MOD = 12;
  public static final int EQ = 31;
  public static final int ARROW = 29;
  public static final int FOREACH = 52;
  public static final int THENELSE = 44;
  public static final int WHILE = 45;
  public static final int LIST = 17;
  public static final int FLOAT = 55;
  public static final int NE = 25;
  public static final int STRUCTURE = 41;
  public static final int LCRO = 18;
  public static final int STRING = 58;
  public static final int LPAR = 4;
  public static final int CIRCUMFLEX = 39;
  public static final int DIFF = 26;
  public static final int MINUS_U = 9;
  public static final int AFF = 13;
  public static final int FALSE = 47;
  public static final int GT = 21;
  public static final int TDOT = 15;
  public static final int PROCEDURE = 2;
  public static final int MINUSS = 38;
}

