
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 06 13:17:37 CEST 2013
//----------------------------------------------------



/** CUP generated interface containing symbol constants. */
public interface Dm1Sym {
  /* terminals */
  public static final int STRING_LITERAL = 45;
  public static final int LBRACKET = 10;
  public static final int MULT = 40;
  public static final int CHAR = 20;
  public static final int GE = 34;
  public static final int SEMIC = 12;
  public static final int INT = 17;
  public static final int ARRAY = 26;
  public static final int MINUS = 38;
  public static final int CHARACTER_LITERAL = 48;
  public static final int AND = 29;
  public static final int LT = 31;
  public static final int RPAR = 7;
  public static final int RECORD = 27;
  public static final int OR = 30;
  public static final int COMMA = 14;
  public static final int DIV = 41;
  public static final int BEGIN = 4;
  public static final int PLUS = 37;
  public static final int TYPEDEF = 3;
  public static final int DOT = 15;
  public static final int LE = 33;
  public static final int EOF = 0;
  public static final int BOOLEAN = 21;
  public static final int AMP = 43;
  public static final int EQUAL = 42;
  public static final int RBRACKET = 11;
  public static final int error = 1;
  public static final int STACK = 23;
  public static final int EQ = 35;
  public static final int ARROW = 28;
  public static final int COLON = 13;
  public static final int LBRACE = 8;
  public static final int APOS = 16;
  public static final int LIST = 22;
  public static final int FLOAT = 18;
  public static final int RBRACE = 9;
  public static final int NE = 36;
  public static final int END = 5;
  public static final int LPAR = 6;
  public static final int STRING = 19;
  public static final int MINUS_U = 39;
  public static final int FLOAT_LITERAL = 47;
  public static final int POINTER = 24;
  public static final int GT = 32;
  public static final int VAR = 2;
  public static final int SET = 25;
  public static final int INTEGER_LITERAL = 46;
  public static final int IDENTIFIER = 44;
}

