/* The following code was generated by JFlex 1.4.3 on 06/05/13 13:17 */

import java_cup.runtime.*;
import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 06/05/13 13:17 from the specification file
 * <tt>/Users/Lionel/Documents/workspace/dm1-corrige/lexer/dm1.lex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRINGLITERAL = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\4\1\0\1\0\1\3\22\0\1\0\1\54\1\52"+
    "\3\0\1\24\1\11\1\14\1\15\1\13\1\0\1\21\1\43\1\7"+
    "\1\12\1\5\11\6\1\23\1\22\1\53\1\51\1\44\2\0\32\1"+
    "\1\20\1\55\1\15\1\0\1\2\1\0\1\33\1\41\1\34\1\47"+
    "\1\10\1\30\1\40\1\35\1\25\1\1\1\50\1\31\1\1\1\26"+
    "\1\32\1\42\1\1\1\36\1\37\1\27\1\1\1\45\2\1\1\46"+
    "\1\1\1\16\1\0\1\17\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\1\2\3\1\4\1\2\1\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\12\2\1\1\1\17\1\2\1\20\1\21"+
    "\1\22\1\1\2\23\1\24\1\25\1\26\1\2\3\0"+
    "\14\2\1\27\1\30\1\2\1\31\1\32\1\33\2\23"+
    "\1\34\1\35\1\36\1\37\1\0\1\40\1\41\2\0"+
    "\1\42\6\2\1\43\5\2\1\44\2\45\1\0\1\23"+
    "\1\0\2\26\1\0\2\2\1\46\1\2\1\47\6\2"+
    "\1\23\1\0\1\2\1\50\1\51\1\2\1\52\1\2"+
    "\1\53\3\2\1\54\1\55\2\2\1\56\1\57\1\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\u0114\0\u0142"+
    "\0\u0170\0\u019e\0\u01cc\0\134\0\134\0\134\0\134\0\134"+
    "\0\134\0\134\0\134\0\134\0\u01fa\0\u0228\0\u0256\0\u0284"+
    "\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a\0\u0398\0\u03c6\0\u03f4"+
    "\0\u0422\0\u0450\0\134\0\u047e\0\u04ac\0\u04da\0\u0508\0\134"+
    "\0\u0536\0\u0564\0\u0592\0\u05c0\0\u05ee\0\u061c\0\u064a\0\u0678"+
    "\0\u06a6\0\u06d4\0\u0702\0\u0730\0\u075e\0\u078c\0\u07ba\0\u07e8"+
    "\0\u0816\0\u0844\0\134\0\134\0\u0872\0\134\0\134\0\134"+
    "\0\u08a0\0\u08ce\0\134\0\134\0\134\0\134\0\u08fc\0\212"+
    "\0\134\0\u092a\0\u0958\0\212\0\u0986\0\u09b4\0\u09e2\0\u0a10"+
    "\0\u0a3e\0\u0a6c\0\212\0\u0a9a\0\u0ac8\0\u0af6\0\u0b24\0\u0b52"+
    "\0\212\0\u0b80\0\134\0\u0bae\0\u0bdc\0\u0c0a\0\134\0\u0c38"+
    "\0\u0c66\0\u0c94\0\u0cc2\0\212\0\u0cf0\0\212\0\u0d1e\0\u0d4c"+
    "\0\u0d7a\0\u0da8\0\u0dd6\0\u0e04\0\u0e32\0\u0e60\0\u0e8e\0\212"+
    "\0\212\0\u0ebc\0\212\0\u0eea\0\212\0\u0f18\0\u0f46\0\u0f74"+
    "\0\212\0\212\0\u0fa2\0\u0fd0\0\212\0\212\0\212";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\3\1\5\1\3\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\3\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\4\1\26"+
    "\1\27\1\30\1\4\1\31\1\32\1\4\1\33\1\34"+
    "\1\4\1\35\1\36\1\37\1\40\1\41\3\4\1\42"+
    "\1\43\1\44\1\45\1\3\3\46\2\0\5\46\1\47"+
    "\37\46\1\50\2\46\1\51\57\0\2\4\2\0\2\4"+
    "\1\0\1\4\14\0\16\4\2\0\4\4\11\0\1\3"+
    "\60\0\1\52\53\0\2\7\1\52\53\0\2\52\50\0"+
    "\2\4\2\0\2\4\1\0\1\4\14\0\1\4\1\53"+
    "\14\4\2\0\4\4\5\0\3\54\2\0\51\54\12\0"+
    "\1\55\1\56\43\0\2\4\2\0\2\4\1\0\1\4"+
    "\14\0\1\4\1\57\14\4\2\0\4\4\6\0\2\4"+
    "\2\0\2\4\1\0\1\4\14\0\16\4\2\0\1\4"+
    "\1\60\2\4\6\0\2\4\2\0\2\4\1\0\1\4"+
    "\14\0\4\4\1\61\11\4\2\0\4\4\6\0\2\4"+
    "\2\0\2\4\1\0\1\4\14\0\1\62\15\4\2\0"+
    "\4\4\6\0\2\4\2\0\2\4\1\0\1\4\14\0"+
    "\11\4\1\63\4\4\2\0\4\4\6\0\2\4\2\0"+
    "\2\4\1\0\1\4\14\0\10\4\1\64\5\4\2\0"+
    "\4\4\6\0\2\4\2\0\2\4\1\0\1\65\14\0"+
    "\16\4\2\0\4\4\6\0\2\4\2\0\2\4\1\0"+
    "\1\66\14\0\2\4\1\67\13\4\2\0\4\4\6\0"+
    "\2\4\2\0\2\4\1\0\1\70\14\0\5\4\1\71"+
    "\10\4\2\0\4\4\6\0\2\4\2\0\2\4\1\0"+
    "\1\4\14\0\5\4\1\72\10\4\2\0\4\4\51\0"+
    "\1\73\62\0\1\74\5\0\2\4\2\0\2\4\1\0"+
    "\1\4\14\0\6\4\1\75\7\4\2\0\4\4\56\0"+
    "\1\76\55\0\1\77\55\0\1\100\4\0\3\46\2\0"+
    "\45\46\1\0\2\46\1\0\3\46\2\0\5\46\1\101"+
    "\1\102\36\46\1\0\2\46\27\0\1\103\1\104\6\0"+
    "\1\105\13\0\1\106\10\0\2\52\1\0\1\107\46\0"+
    "\2\4\2\0\2\4\1\0\1\4\14\0\16\4\2\0"+
    "\2\4\1\110\1\4\16\0\1\111\44\0\3\55\1\5"+
    "\1\3\51\55\13\112\1\113\42\112\1\0\2\4\2\0"+
    "\2\4\1\0\1\4\14\0\2\4\1\114\13\4\2\0"+
    "\4\4\6\0\2\4\2\0\2\4\1\0\1\4\14\0"+
    "\15\4\1\115\2\0\4\4\6\0\2\4\2\0\2\4"+
    "\1\0\1\4\14\0\5\4\1\116\10\4\2\0\4\4"+
    "\6\0\2\4\2\0\2\4\1\0\1\4\14\0\12\4"+
    "\1\117\3\4\2\0\4\4\6\0\2\4\2\0\2\4"+
    "\1\0\1\4\14\0\11\4\1\120\4\4\2\0\4\4"+
    "\6\0\2\4\2\0\2\4\1\0\1\4\14\0\6\4"+
    "\1\121\7\4\2\0\4\4\6\0\2\4\2\0\2\4"+
    "\1\0\1\4\14\0\7\4\1\122\6\4\2\0\4\4"+
    "\6\0\2\4\2\0\2\4\1\0\1\4\14\0\2\4"+
    "\1\123\13\4\2\0\4\4\6\0\2\4\2\0\2\4"+
    "\1\0\1\4\14\0\6\4\1\124\2\4\1\125\4\4"+
    "\2\0\4\4\6\0\2\4\2\0\2\4\1\0\1\4"+
    "\14\0\13\4\1\126\2\4\2\0\4\4\6\0\2\4"+
    "\2\0\2\4\1\0\1\4\14\0\5\4\1\127\10\4"+
    "\2\0\4\4\6\0\2\4\2\0\2\4\1\0\1\4"+
    "\14\0\1\130\15\4\2\0\4\4\6\0\2\4\2\0"+
    "\2\4\1\0\1\4\14\0\11\4\1\131\4\4\2\0"+
    "\4\4\5\0\3\101\1\132\1\133\45\101\1\134\2\101"+
    "\1\134\3\135\2\136\6\135\1\46\36\135\1\136\2\135"+
    "\1\136\5\0\1\137\1\140\47\0\13\112\1\141\42\112"+
    "\12\0\1\3\1\113\43\0\2\4\2\0\2\4\1\0"+
    "\1\142\14\0\16\4\2\0\4\4\6\0\2\4\2\0"+
    "\2\4\1\0\1\4\14\0\6\4\1\143\7\4\2\0"+
    "\4\4\6\0\2\4\2\0\2\4\1\0\1\4\14\0"+
    "\2\4\1\144\13\4\2\0\4\4\6\0\2\4\2\0"+
    "\2\4\1\0\1\4\14\0\6\4\1\145\7\4\2\0"+
    "\4\4\6\0\2\4\2\0\2\4\1\0\1\4\14\0"+
    "\11\4\1\146\4\4\2\0\4\4\6\0\2\4\2\0"+
    "\2\4\1\0\1\4\14\0\5\4\1\147\10\4\2\0"+
    "\4\4\6\0\2\4\2\0\2\4\1\0\1\4\14\0"+
    "\7\4\1\150\6\4\2\0\4\4\6\0\2\4\2\0"+
    "\2\4\1\0\1\4\14\0\1\151\15\4\2\0\4\4"+
    "\6\0\2\4\2\0\2\4\1\0\1\4\14\0\1\152"+
    "\15\4\2\0\4\4\6\0\2\4\2\0\2\4\1\0"+
    "\1\4\14\0\4\4\1\153\11\4\2\0\4\4\6\0"+
    "\2\4\2\0\2\4\1\0\1\4\14\0\1\4\1\154"+
    "\14\4\2\0\4\4\11\0\1\133\51\0\3\134\1\132"+
    "\1\133\51\134\3\135\2\136\6\135\1\155\36\135\1\136"+
    "\2\135\14\136\1\156\42\136\5\0\2\140\47\0\12\112"+
    "\1\3\1\141\42\112\1\0\2\4\2\0\2\4\1\0"+
    "\1\4\14\0\16\4\2\0\2\4\1\157\1\4\6\0"+
    "\2\4\2\0\2\4\1\0\1\4\14\0\2\4\1\160"+
    "\13\4\2\0\4\4\6\0\2\4\2\0\2\4\1\0"+
    "\1\4\14\0\16\4\2\0\1\4\1\161\2\4\6\0"+
    "\2\4\2\0\2\4\1\0\1\4\14\0\11\4\1\162"+
    "\4\4\2\0\4\4\6\0\2\4\2\0\2\4\1\0"+
    "\1\4\14\0\16\4\2\0\3\4\1\163\6\0\2\4"+
    "\2\0\2\4\1\0\1\4\14\0\1\4\1\164\14\4"+
    "\2\0\4\4\6\0\2\4\2\0\2\4\1\0\1\4"+
    "\14\0\1\4\1\165\14\4\2\0\4\4\6\0\2\4"+
    "\2\0\2\4\1\0\1\166\14\0\16\4\2\0\4\4"+
    "\6\0\2\4\2\0\2\4\1\0\1\4\14\0\2\4"+
    "\1\167\13\4\2\0\4\4\5\0\3\135\2\136\5\135"+
    "\1\46\1\155\36\135\1\136\2\135\13\136\1\133\1\156"+
    "\42\136\1\0\2\4\2\0\2\4\1\0\1\170\14\0"+
    "\16\4\2\0\4\4\6\0\2\4\2\0\2\4\1\0"+
    "\1\4\14\0\16\4\2\0\2\4\1\171\1\4\6\0"+
    "\2\4\2\0\2\4\1\0\1\4\14\0\13\4\1\172"+
    "\2\4\2\0\4\4\6\0\2\4\2\0\2\4\1\0"+
    "\1\4\14\0\6\4\1\173\7\4\2\0\4\4\6\0"+
    "\2\4\2\0\2\4\1\0\1\174\14\0\16\4\2\0"+
    "\4\4\6\0\2\4\2\0\2\4\1\0\1\4\14\0"+
    "\3\4\1\175\12\4\2\0\4\4\6\0\2\4\2\0"+
    "\2\4\1\0\1\4\14\0\1\4\1\176\14\4\2\0"+
    "\4\4\6\0\2\4\2\0\2\4\1\0\1\4\14\0"+
    "\11\4\1\177\4\4\2\0\4\4\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4094];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\10\1\11\11\16\1\1\11\4\1\1\11"+
    "\3\1\3\0\14\1\2\11\1\1\3\11\2\1\4\11"+
    "\1\0\1\1\1\11\2\0\17\1\1\11\1\0\1\1"+
    "\1\0\1\11\1\1\1\0\14\1\1\0\21\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
private Symbol symbol (int type) {
    return new Symbol (type, yyline, yycolumn);
}

private Symbol symbol (int type, Object value) {
    return new Symbol (type, yyline, yycolumn, value);
}

StringBuffer string = new StringBuffer();

boolean traceLex=true;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { /* ignore */
          }
        case 49: break;
        case 10: 
          { if (traceLex) System.err.println("LBRACKET");return symbol(Symbols.LBRACKET);
          }
        case 50: break;
        case 15: 
          { if (traceLex) System.err.println("GT");return symbol(Symbols.GT);
          }
        case 51: break;
        case 16: 
          { if (traceLex) System.err.println("EQUAL");return symbol(Symbols.EQUAL);
          }
        case 52: break;
        case 13: 
          { if (traceLex) System.err.println("COLON");return symbol(Symbols.COLON);
          }
        case 53: break;
        case 5: 
          { if (traceLex) System.err.println("APOS");return symbol(Symbols.APOS);
          }
        case 54: break;
        case 38: 
          { if (traceLex) System.err.println("LIST");return symbol(Symbols.LIST);
          }
        case 55: break;
        case 32: 
          { if (traceLex) System.err.println("END");return symbol(Symbols.END);
          }
        case 56: break;
        case 34: 
          { if (traceLex) System.err.println("INT");return symbol(Symbols.INT);
          }
        case 57: break;
        case 40: 
          { if (traceLex) System.err.println("FLOAT");return symbol(Symbols.FLOAT);
          }
        case 58: break;
        case 17: 
          { string.setLength(0); yybegin(STRINGLITERAL);
          }
        case 59: break;
        case 20: 
          { yybegin(YYINITIAL);
							   if (traceLex) System.err.println("STRING LITERAL : " + string.toString()); return symbol(Symbols.STRING_LITERAL, string.toString());
          }
        case 60: break;
        case 29: 
          { string.append('\t');
          }
        case 61: break;
        case 45: 
          { if (traceLex) System.err.println("STRING");return symbol(Symbols.STRING);
          }
        case 62: break;
        case 42: 
          { if (traceLex) System.err.println("STACK");return symbol(Symbols.STACK);
          }
        case 63: break;
        case 27: 
          { if (traceLex) System.err.println("NE");return symbol(Symbols.NE);
          }
        case 64: break;
        case 26: 
          { if (traceLex) System.err.println("LE");return symbol(Symbols.LE);
          }
        case 65: break;
        case 14: 
          { if (traceLex) System.err.println("AMP");return symbol(Symbols.AMP);
          }
        case 66: break;
        case 23: 
          { if (traceLex) System.err.println("ARROW");return symbol(Symbols.ARROW);
          }
        case 67: break;
        case 4: 
          { if (traceLex) System.err.println("DOT");return symbol(Symbols.DOT);
          }
        case 68: break;
        case 43: 
          { if (traceLex) System.err.println("BEGIN");return symbol(Symbols.BEGIN);
          }
        case 69: break;
        case 21: 
          { string.append('\\');
          }
        case 70: break;
        case 3: 
          { if (traceLex) System.err.println("INTEGER LITERAL : " + yytext());return symbol(Symbols.INTEGER_LITERAL, Integer.parseInt(yytext()));
          }
        case 71: break;
        case 30: 
          { string.append('\r');
          }
        case 72: break;
        case 6: 
          { if (traceLex) System.err.println("LPAR");return symbol(Symbols.LPAR);
          }
        case 73: break;
        case 11: 
          { if (traceLex) System.err.println("COMMA");return symbol(Symbols.COMMA);
          }
        case 74: break;
        case 37: 
          { /* nothing */
          }
        case 75: break;
        case 31: 
          { string.append('\"');
          }
        case 76: break;
        case 41: 
          { if (traceLex) System.err.println("ARRAY");return symbol(Symbols.ARRAY);
          }
        case 77: break;
        case 12: 
          { if (traceLex) System.err.println("SEMIC");return symbol(Symbols.SEMIC);
          }
        case 78: break;
        case 22: 
          { if (traceLex) System.err.println("FLOAT LITERAL : " + yytext());return symbol(Symbols.FLOAT_LITERAL, Double.parseDouble(yytext()));
          }
        case 79: break;
        case 18: 
          { if (traceLex) System.err.println("LT");return symbol(Symbols.LT);
          }
        case 80: break;
        case 35: 
          { if (traceLex) System.err.println("SET");return symbol(Symbols.SET);
          }
        case 81: break;
        case 9: 
          { if (traceLex) System.err.println("RBRACE");return symbol(Symbols.RBRACE);
          }
        case 82: break;
        case 8: 
          { if (traceLex) System.err.println("LBRACE");return symbol(Symbols.LBRACE);
          }
        case 83: break;
        case 33: 
          { if (traceLex) System.err.println("CHARACTER LITERAL");return symbol(Symbols.CHARACTER_LITERAL, yytext().charAt(1));
          }
        case 84: break;
        case 24: 
          { if (traceLex) System.err.println("GE");return symbol(Symbols.GE);
          }
        case 85: break;
        case 28: 
          { string.append('\n');
          }
        case 86: break;
        case 19: 
          { string.append(yytext());
          }
        case 87: break;
        case 7: 
          { if (traceLex) System.err.println("RPAR");return symbol(Symbols.RPAR);
          }
        case 88: break;
        case 25: 
          { if (traceLex) System.err.println("EQ");return symbol(Symbols.EQ);
          }
        case 89: break;
        case 36: 
          { if (traceLex) System.err.println("VAR");return symbol(Symbols.VAR);
          }
        case 90: break;
        case 46: 
          { if (traceLex) System.err.println("TYPEDEF");return symbol(Symbols.TYPEDEF);
          }
        case 91: break;
        case 39: 
          { if (traceLex) System.err.println("CHAR");return symbol(Symbols.CHAR);
          }
        case 92: break;
        case 2: 
          { if (traceLex) System.err.println("IDENTIFIER");return symbol(Symbols.IDENTIFIER, yytext());
          }
        case 93: break;
        case 48: 
          { if (traceLex) System.err.println("POINTER");return symbol(Symbols.POINTER);
          }
        case 94: break;
        case 44: 
          { if (traceLex) System.err.println("RECORD");return symbol(Symbols.RECORD);
          }
        case 95: break;
        case 47: 
          { if (traceLex) System.err.println("BOOLEAN");return symbol(Symbols.BOOLEAN);
          }
        case 96: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(Symbols.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
